[package]
name = "twitch-api"
version = "0.1.0"
authors = ["Josiah Hilden <jhilden13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
reqwest = { version = "0.10", features = [ "json" ] }
tokio = { version = "0.2", features = [ "full" ] }
time = { version = "0.2", default-features = false, features = [ "std", "serde" ] }
structopt = "0.3"
pretty_env_logger = "0.4"
log = "0.4"

