name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug 

jobs:
  builds-stable:
    environment: Testing
    env:
      TWITCH_API_RS_TEST_CLIENT_ID: ${{ secrets.TWITCH_API_RS_TEST_CLIENT_ID }}
      TWITCH_API_RS_TEST_CLIENT_SECRET: ${{ secrets.TWITCH_API_RS_TEST_CLIENT_SECRET }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
